version: 2

my-profile:
  outputs:
    dev:
      type: bigquery
      project: projeto-final-331612
      dataset:  adventureworks_etl
      location: US
sources:
  - name:  adventureworks_etl
    tables:
      - name: address
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: person
      - name: product
      - name: productcategory
      - name: productsubcategory
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
