
version: 2

models:
    - name: fact_ordersproducts
      description: "A starter dbt model"
      columns:
          - name: salesorderheaderSK

    - name: fact_ordersreason
      description: "A starter dbt model"
      columns:
          - name: salesorderheaderSK

    - name: dim_products
      description: "A starter dbt model"
      columns:
          - name: produtoid

    - name: dim_salesorderheader
      description: "A starter dbt model"
      columns:
          - name: salesorderid

    - name: dim_address
      description: "A starter dbt model"
      columns:
          - name: addressid

    - name: dim_salesreason
      description: "A starter dbt model"
      columns:
          - name: salesreasonid